language: objective-c
osx_image: xcode7.1

install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild test -workspace Example/SuperMock.xcworkspace -scheme SuperMock-Example -destination "platform=iOS Simulator,name=iPhone 6" ONLY_ACTIVE_ARCH=YES | xcpretty -c
- pod lib lint --quick
